server:
    encoding:
      charset: utf-8
      enabled: true

spring:
  jpa:
    database: oracle
    hibernate:
      ddl-auto: create
    generate-ddl: false
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        dialect: org.hibernate.dialect.OracleDialect

  config:
    import:
      - classpath:/config/secret.yml

logging:
  pattern:
    file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    org.hibernate.SQL: off
    org.hibernate.type.descriptor.sql.BasicBinder: off
    org.hibernate.type.descriptor.sql.BasicExtractor: off
    root: info
  file:
    name: log/application.log


