server:
    encoding:
      charset: utf-8
      enabled: true

spring:
  config:
    import:
      - classpath:/config/secret.yml

logging:
  pattern:
    file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    org.hibernate.SQL: off
    org.hibernate.type.descriptor.sql.BasicBinder: off
    org.hibernate.type.descriptor.sql.BasicExtractor: off
    root: info
#  file:
#    name: log/application.log


